### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by r-ce** [Ozelotick/PremiumSDK#1]
the sdk has problems when compiling not sure if this problem caused by me

**Comment by NoireCS** [comment]
Maybe you should post the errors or we can't help you.

**Comment by r-ce** [comment]
![image](https://user-images.githubusercontent.com/35370866/39642324-10b08082-4fda-11e8-8ee7-b658269320dd.png)
i have a feeling that i either missed something or im just retarded
